Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
  end

  config.vm.provision :itamae do |config|
    config.sudo = true
    config.shell = "/bin/bash"
    config.recipes = ["./recipe.rb"]
  end
end
